[package]
name = "orca-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description = "Orca: a high-performance exhaustive crossword grid filler"

[lints]
workspace = true

[[bin]]
name = "orca"
path = "src/main.rs"

[dependencies]
orca-core.workspace = true
orca-solver.workspace = true
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
dialoguer.workspace = true
